INSERT INTO Authors (first_name, last_name)
VALUES
('', 'Homer'),
('Publije', 'Vergilije Maron'),
('Marko', 'Aurelije'),
('', 'Sofoklo'),
('', 'Platon'),
('Aurelije', 'Augustin'),
('Dante', 'Alighieri'),
('Francesco', 'Petrarca'),
('Marin', 'Držić'),
('Marko', 'Marulić'),
('Petar', 'Zoranić'),
('William', 'Shakespeare'),
('Miguel', 'de Cervantes'),
('Ivan', 'Gundulić'),
('Johann Wolfgang', 'von Goethe'),
('Lav Nikolajevič', 'Tolstoj'),
('Fjodor Mihajlovič', 'Dostojevski'),
('Edgar Allan', 'Poe'),
('Vjenceslav', 'Novak'),
('Miroslav', 'Krleža'),
('George', 'Orwell'),
('Ranko', 'Marinković'),
('Franz', 'Kafka'),
('J.R.R.', 'Tolkien')
