INSERT INTO Authors (first_name, last_name)
VALUES
('', 'Homer'),
('Publije', 'Vergilije Maron'),
('Marko', 'Aurelije'),
('', 'Sofoklo'),
('', 'Platon'),
('Publije', 'Ovidije Nazon'),
('Aurelije', 'Augustin'),
('Dante', 'Alighieri'),
('Giovanni', 'Boccaccio'),
('Francesco', 'Petrarca'),
('Marin', 'Držić'),
('Marko', 'Marulić'),
('Petar', 'Zoranić'),
('William', 'Shakespeare'),
('Miguel', 'de Cervantes'),
('Ivan', 'Gundulić'),
('John', 'Milton'),
('', 'Moliere'),
('Friedrich', 'Schiller'),
('Johann Wolfgang', 'von Goethe'),
('Lav Nikolajevič', 'Tolstoj'),
('Nikolaj Vasiljevič', 'Gogolj'),
('Fjodor Mihajlovič', 'Dostojevski'),
('Edgar Allan', 'Poe'),
('Alexandre', 'Dumas'),
('Emily', 'Brontë'),
('Herman', 'Melville'),
('Honoré de', 'Balzac'),
('Daniel', 'Defoe'),
('Gustave', 'Flaubert'),
('Mark', 'Twain'),
('Antoine de', 'Saint-Exupéry'),
('Victor', 'Hugo'),
('Mary', 'Shelley'),
('Bram', 'Stoker'),
('Vjenceslav', 'Novak'),
('August', 'Šenoa'),
('Ante', 'Kovačić'),
('Miroslav', 'Krleža'),
('George', 'Orwell'),
('Ranko', 'Marinković'),
('Franz', 'Kafka'),
('J.D.', 'Salinger'),
('F. Scott', 'Fitzgerald'),
('James', 'Joyce'),
('Charles', 'Dickens'),
('John', 'Bunyan'),
('Jane', 'Austen'),
('Albert', 'Camus'),
('J.R.R.', 'Tolkien'),
('Marcel', 'Proust'),
('C.S.', 'Lewis'),
('Oscar', 'Wilde'),
('Harper', 'Lee'),
('Aldous', 'Huxley'),
('Ray', 'Bradbury'),
('Ernest', 'Hemingway'),
('J.K.', 'Rowling'),
('Louisa May', 'Alcott'),
('Agatha', 'Christie'),
('Gabriel Garcia', 'Marquez'),
('Petar', 'Hektorović')
